services:
  postgres-db:
    image: postgres:15-alpine
    container_name: 'parcial-db'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'parcial-backend'
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres-db

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres-db

volumes:
  postgres_data:

